spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://localhost:3306/scan_db
    username: root
    password: my-secret-pw
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
    addresses: ${amqpURL:amqp://guest:guest@localhost}

broker:
  prefix: default
  queues:
    receipt:
      name: ${broker.prefix}.receipt-scan
    catalog:
      name: ${broker.prefix}.product
    user:
      name: ${broker.prefix}.store
  exchanges:
    receipt:
      name: direct.receipt-scan
      type: direct
    catalog:
      name: direct.catalog
      type: direct
    user:
      name: direct.user
      type: direct
  bindings:
    receipt:
      exchange: ${broker.exchanges.receipt.name}
      queue: ${broker.queues.receipt.name}
      routingKey: ${broker.queues.receipt.name}
    catalog:
      exchange: ${broker.exchanges.catalog.name}
      queue: ${broker.queues.catalog.name}
      routingKey: ${broker.queues.catalog.name}
    user:
      exchange: ${broker.exchanges.user.name}
      queue: ${broker.queues.user.name}
      routingKey: ${broker.queues.user.name}
