spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    addresses: ${amqpURL:amqp://guest:guest@localhost}

broker:
  prefix: default
  queues:
    receipt:
      name: ${broker.prefix}.receipt-scan
  exchanges:
    receipt:
      name: direct.receipt-scan
      type: direct
  bindings:
    receipt:
      exchange: ${broker.exchanges.receipt.name}
      queue: ${broker.queues.receipt.name}
      routingKey: ${broker.queues.receipt.name}
