spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
    addresses: ${amqpURL:amqp://guest:guest@localhost}

broker:
  prefix: default
  queues:
    receipt:
      name: ${broker.prefix}.receipt-scan
  exchanges:
    receipt:
      name: direct.receipt-scan
      type: direct
  bindings:
    receipt:
      exchange: ${broker.exchanges.receipt.name}
      queue: ${broker.queues.receipt.name}
      routingKey: ${broker.queues.receipt.name}
