server:
  port: 8082

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/nota-social
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: password
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#    addresses: ${amqpURL:amqp://guest:guest@localhost}

  datasource:
#    url: jdbc:mysql://localhost:3306/scan_db?createIfNotExist=true
#    username: root
#    password: my-secret-pw
#    To use local
    url: jdbc:mysql://localhost:3306/receipt_scan_db?createIfNotExists=true
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

broker:
  prefix: default
  queues:
    receipt:
      name: ${broker.prefix}.receipt-scan
    processed-receipt:
      name: ${broker.prefix}.processed-receipt
  exchanges:
    receipt:
      name: direct.receipt-scan
      type: direct
    processed-receipt:
      name: direct.processed-receipt
      type: direct
  bindings:
    receipt:
      exchange: ${broker.exchanges.receipt.name}
      queue: ${broker.queues.receipt.name}
      routingKey: ${broker.queues.receipt.name}
    processed-receipt:
      exchange: ${broker.exchanges.processed-receipt.name}
      queue: ${broker.queues.processed-receipt.name}
      routingKey: ${broker.queues.processed-receipt.name}
